sudo: false

language:
    - php
    - node_js

php:
  - nightly
  - 5.6
  #- 5.5
  #- 5.4
  - 7
  #- hhvm

node_js:
  - "6"

cache:
  apt: true
  directories:
   - bower_components
   - node_modules

env:
  - TRAVIS_NODE_VERSION="6" CXX="g++-4.8"
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

matrix:
  fast_finish: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
    - git submodule update --init --recursive
    - composer self-update && composer --version

install:
    - nvm install node 6
    - nvm use node 6
    - node -v && npm -v
    - npm install -g npm@latest
    - npm install -g bower gulp
    - npm install
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - composer global require squizlabs/php_codesniffer
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh
    - npm run build
    - npm run build:production
    - npm run jshint
    - npm run eslint
    #- phpcs --standard=ruleset.xml --extensions=php -n -s .

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh
