language:
    - php
    - node_js

dist: trusty
sudo: required

php:
  - nightly
  - 7.1
  - 7.2

node_js:
  - "8"
  - "9"

cache:
  # yarn: true
  apt: true
  directories:
   # - node_modules
   # - $HOME/.composer/cache
   # - $HOME/.yarn-cache
   # - vendor

env:
  - TRAVIS_NODE_VERSION="8" WP_VERSION=latest WP_MULTISITE=0
  - TRAVIS_NODE_VERSION="8" WP_VERSION=latest WP_MULTISITE=1

matrix:
  fast_finish: true
  allow_failures:
     - php: nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
    - composer self-update && composer --version
    - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update && sudo apt-get install yarn

install:
    - node -v && npm -v && yarn --version
    - npm install
    - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
    - npm run build:dev
    - npm run build
