language:
    - php
    - node_js

dist: trusty
sudo: required

php:
  - nightly
  - 7.3
  - 7.4

node_js:
  - "12"
  - "14"

cache:
  apt: true
  directories:
   # - node_modules
   # - $HOME/.composer/cache
   # - vendor

env:
  - TRAVIS_NODE_VERSION=12
  - TRAVIS_NODE_VERSION=14

matrix:
  fast_finish: true
  allow_failures:
     - php: nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
    - npm i -g npm && composer self-update && composer --version
    - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION

install:
    - node -v && npm -v
    - npm install
    - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
    - npm run build:dev
    - npm run build
