language:
    - php
    - node_js

sudo: false

dist: trusty

php:
  - nightly
  - 7
  - 7.1
  - 7.2

node_js:
  - "8"

cache:
  yarn: true
  apt: true
  directories:
   - node_modules
   - $HOME/.composer/cache
   - $HOME/.yarn-cache
   - vendor

env:
  - TRAVIS_NODE_VERSION="8" WP_VERSION=latest WP_MULTISITE=0
  - TRAVIS_NODE_VERSION="8" WP_VERSION=latest WP_MULTISITE=1

matrix:
  fast_finish: true
  allow_failures:
     - php: nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
    - composer self-update && composer --version
    - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
    - export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh | bash

install:
    - node -v && npm -v && yarn --version
    - travis_retry yarn
    - npm list webpack
    - npm install
    - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
    - yarn run build
    - yarn run build:dev
