sudo: false

language:
    - php
    - node_js

php:
  #- nightly
  #- 5.6
  #- 5.5
  #- 5.4
  - 7
  #- hhvm

cache:
  directories:
    - bower_components
    - node_modules

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=trunk WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=1

before_script:
   - git submodule update --init --recursive

install:
    - npm install -g npm@latest
    - npm install -g bower gulp jscs
    - npm install
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh
